### ISSUE TITLE
Error rendering jinja template caused by NoSuchProcess

### ISSUE THREAD

**Issue by Holm78** [thingswise/tw-etcdstat#2]
```
сен 17 11:39:50 demo2 python[3049]: ERROR:root:Error rendering {{unit("kubelet.service").cgroup.rss}}
сен 17 11:39:50 demo2 python[3049]: Traceback (most recent call last):
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib/python2.7/site-packages/etcdstat/etcdstat.py", line 189, in update_etcd
сен 17 11:39:50 demo2 python[3049]: _value = value.render(ctx)
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib/python2.7/site-packages/etcdstat/etcdstat.py", line 127, in render
сен 17 11:39:50 demo2 python[3049]: return self.template.render(context)
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 1008, in render
сен 17 11:39:50 demo2 python[3049]: return self.environment.handle_exception(exc_info, True)
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
сен 17 11:39:50 demo2 python[3049]: reraise(exc_type, exc_value, tb)
сен 17 11:39:50 demo2 python[3049]: File "<template>", line 1, in top-level template code
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
сен 17 11:39:50 demo2 python[3049]: return getattr(obj, attribute)
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib/python2.7/site-packages/etcdstat/systemd.py", line 73, in rss
сен 17 11:39:50 demo2 python[3049]: memory += _get_process(pid).memory_info().rss
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib/python2.7/site-packages/cachetools/__init__.py", line 46, in wrapper
сен 17 11:39:50 demo2 python[3049]: v = func(*args, **kwargs)
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib/python2.7/site-packages/etcdstat/systemd.py", line 32, in _get_process
сен 17 11:39:50 demo2 python[3049]: return psutil.Process(pid=pid)
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 442, in __init__
сен 17 11:39:50 demo2 python[3049]: self._init(pid)
сен 17 11:39:50 demo2 python[3049]: File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 482, in _init
сен 17 11:39:50 demo2 python[3049]: raise NoSuchProcess(pid, None, msg)
сен 17 11:39:50 demo2 python[3049]: NoSuchProcess: psutil.NoSuchProcess no process found with pid 21936
```

**Comment by Holm78** [comment]
Implemented in 0.1.1.post25
